#.travis.yml

notifications:
  enmail:
    on_success: never
    on_failure: always
branches:
  only:
      - master
git:
  submodules: false
addons:
 apt:
    packages:
      - curl
      - wget
      - zip


language: node_js
node_js:
  - 8

before_install:
  - npm i -g npm@5.3.0
script:
  - npm test
  - npm run-script build
after_success:
  - bash ./after_success.sh