#.travis.yml

notifications:
  enmail:
    on_success: never
    on_failure: always
git:
  submodules: false
addons:
 apt:
    packages:
      - curl
      - wget
      - zip


language: node_js
node_js:
  - 8
branches:
  only:
      - master
before_install:
  - npm i -g npm@5.3.0


script:
    - npm test
    - npm run-script build
#    - bash deploy.sh

env:
  - GH_USER_NAME=onoie
  - GH_USER_EMAIL=onoie3@gmail.com
after_success:
  - |

    $(npm bin)/set-up-ssh --key "$encrypted_c773c3304006_key" \
                       --iv "$encrypted_c773c3304006_iv" \
                       --path-encrypted-key ".travis/github_deploy_key.enc"